### PR TITLE
Update main.astro

### PR DESCRIPTION
**Pull request by shindodkar**
# Pull request for # 

## Definition Of Done  

- [ ] Meets acceptance criteria of story / Fixed bug
- [ ] Added new tests
- [ ] Updated documentation

### CODE REVIEW

**Comment by Marvin-Brouwer** [comment]
Hi @shindodkar,

I've got some comments on your change, but I don't want to make this a back-and-forth through GitHub.
Are you open to have a call in discord?
I'd like to walk through the code by screen sharing and maybe doing some pair programming after.

I can do this Thursday (20-04-2023) at 17:30 CEST until about 18:30 CEST.
Let's do discord: https://discord.com/channels/958295823001722890/1097910710501126224.

Let me know if that doesn't work out and we'll find a different date

**Comment by shindodkar** [comment]
Yeah, I would like to work on this. But one problem, if the time get shifted to 12.00pm  CEST will be suitable for me.

**Comment by Marvin-Brouwer** [comment]
Hmm, I have to work during the day.
What timezone do you live?

**Comment by Marvin-Brouwer** [comment]
@shindodkar what timezone do you live, and, what days are generally the best to have a chat?

**Comment by Marvin-Brouwer** [comment]
@shindodkar are you still interested?
Otherwise I'll close the PR and pick it up later myself.

**Comment by Marvin-Brouwer** [comment]
@shindodkar If you are still interested could you please provide me your timezone so I can have a look what works out best for the both of us?

**Pull request closed without merging**
